baseURL = '/'
languageCode = 'en-us'
title = 'My Blog'
format = 'Monday, Jan 2, 2006 3:04 PM'

# [permalinks]
  # blogs = "/:filename/"

pygmentsUseClasses = true
pygmentsCodefences = true

[markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  tabWidth = 2
  noClasses = false

