baseURL = '/'
languageCode = 'en-us'
title = 'My Blog'
format = 'Monday, Jan 2, 2006 3:04 PM'

# [permalinks]
  # blogs = "/:filename/"

[markup.highlight]
  codeFences = true
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  tabWidth = 2
  noClasses = false



